### ISSUE TITLE
Releasing trained weights

### ISSUE THREAD

**Issue by vishaal27** [hammoudhasan/SynthCLIP#1]
Hey, thanks for the great work and releasing the dataset---it is super useful to the community.
Do you have an estimate of when you are planning on releasing the different trained SynthCLIP models? I am mostly interested in the SynthCLIP-10M, 20M and 30M models. 
Thanks again!

**Comment by hammoudhasan** [comment]
Hello @vishaal27 ! SynthCLIP trained on 30M samples is out. I'll add the other two models in around 30 minutes. Will you posted (: !

**Comment by hammoudhasan** [comment]
Done. All uploaded. Let me know if you need anything else.

**Comment by vishaal27** [comment]
Great thanks so much!
