### ISSUE TITLE
Loading the trained parameters into official CLIP model.

### ISSUE THREAD

**Issue by mdokamura-lmd** [hammoudhasan/SynthCLIP#2]
Thank you for your impactful work.

I want to load the trained parameters ([checkpoint_best.pt](https://drive.google.com/drive/folders/1sBnbczyDJUuGMKDOYeN0cOHYcq5L5xhr?usp=sharing)) from SynthCLIP into the official CLIP model.
However, it does not work because the key names are different (probably on the vision encoder side).
Please let me know if you have any ideas.

```
#This is the official CLIP.
device = "cuda" if torch.cuda.is_available() else "cpu"
model, preprocess = clip.load("ViT-B/16", device=device)

#I want to load the parameters like this.
checkpoint = torch.load("checkpoint_best.pt")
model.load_state_dict(checkpoint["state_dict"])
```

Thanks.

**Comment by fabvio** [comment]
Thanks for your interest. That is because we didn't use the official CLIP code for training. We will release very soon further instructions about how to load and use the weights.

**Comment by hammoudhasan** [comment]
@mdokamura-lmd this sample script should do the job!

```
from models import CLIP_VITB16
import torch

# load model instance
model = torch.nn.DataParallel(CLIP_VITB16())

# load checkpoint
checkpoint_path = "./checkpoint_best.pt"
checkpoint = torch.load(checkpoint_path, map_location="cpu")
load_status = model.load_state_dict(checkpoint["state_dict"])

print(load_status)
```

Please let me know if you have any other questions. If not let me know so I can close the issue.
