### ISSUE TITLE
Use of pre-trained model

### ISSUE THREAD

**Issue by YuetianW** [hammoudhasan/SynthCLIP#3]
Hi, can I ask how I can easily call pre-trained models? Just like using Open_CLIP.🤨
Thanks again for your outstanding work! ✨

**Comment by hammoudhasan** [comment]
Hello @YuetianW ! Please refer to issue #2 - where we show how to load the model. Afterwards for inference you can use `.encode_text` and `.encode_image` similar to OpenCLIP. Let me know if you have any further questions so I can close the issue (: !

**Comment by fabvio** [comment]
I integrated the instructions in the readme for clarity. Thanks!

**Comment by YuetianW** [comment]
Got it!
Thanks for your reply!
