### ISSUE TITLE
Evaluation Code

### ISSUE THREAD

**Issue by renos** [hammoudhasan/SynthCLIP#5]
Do you have plans to publish the code used to evaluate the clip models for table 1?

**Comment by hammoudhasan** [comment]
@renos for evaluations we used the code provided by:

* [FS/LP Evaluation](https://github.com/mbanani/lgssl): For fine-grained evaluation LP and FS.

* [LAION CLIP Benchmark](https://github.com/LAION-AI/CLIP_benchmark): For image and text retrieval results.

* ImageNet Zero Shot Results are logged by the code itself.


Let me know if you have further questions!
